version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: python auth/auth_server.py
    ports: ["5000:5000"]
    env_file: .env

  calendar:
    build:
      context: .
      dockerfile: docker_files/calendar.Dockerfile
    ports: ["8001:8001"]
    env_file: .env

  gmail:
    build:
      context: .
      dockerfile: docker_files/gmail.Dockerfile
    ports: ["8002:8002"]
    env_file: .env

  meet:
    build:
      context: .
      dockerfile: docker_files/meet.Dockerfile
    ports: ["8003:8003"]
    env_file: .env

  sheets:
    build:
      context: .
      dockerfile: docker_files/sheets.Dockerfile
    ports: ["8004:8004"]
    env_file: .env
